### ISSUE TITLE
Your work is wonderful!

### ISSUE THREAD

**Issue by it33** [cloudfoundry-community/mattermost-boshrelease#1]
Mattermost core team here, your work looks terrific! 

Would you be open to having us share about your work with the community? 

We try to [list](http://www.mattermost.org/installation/) and tweet about projects that can be of benefit to users,

**Comment by drnic** [comment]
Hey @it33 happy to have you share it around. I just fixed the CI pipeline and v2 now includes the latest `v1.2.0-rc2` pre-release.

**Comment by drnic** [comment]
The CI pipeline doesn't yet run any smoke tests on the deployment, it stops at just running a single node and confirms that that works.

```
  Started updating job mattermost > mattermost/0 (canary). Done (00:00:09)
```

Unfortunately because `testflight` ci job exposes credentials I've made it private. But here's a look at it passing at moment:

![image](https://cloud.githubusercontent.com/assets/108/11153075/4d6ef33a-89eb-11e5-9020-6dbd96ad0f66.png)

**Comment by drnic** [comment]
@it33 if you have any smoke tests that we can run against a deployment to confirm it is working after an upgrade, let me know and I'll add them to our pipeline to test our releases before we cut them.

**Comment by drnic** [comment]
I'd like to test upgrades - from v1 to v2 etc in future too.

**Comment by drnic** [comment]
Correction: v3 now includes v1.2.0 that just came out https://github.com/cloudfoundry-community/mattermost-boshrelease/releases/tag/v3

**Comment by it33** [comment]
@drnic, fantastic!!

We don't have smoke tests documented, but we should ([ticket filed](https://mattermost.atlassian.net/browse/PLT-1164). Each month we push our RC candidates to https://gitlab.mattermost.com/community and we have nightly builds on our community server (please join us!): https://pre-release.mattermost.com/core/

We do [have an upgrade guide](https://github.com/mattermost/platform/blob/master/doc/install/Upgrade-Guide.md), and would love your help testing. We ship on the 16th of the month, and aim to get Release Candidates out 5 working days prior. Working on documenting all this better...

Super excited about your work!
