### ISSUE TITLE
v6.6.0 - mattermost-load-test errand failing - blobstore error

### ISSUE THREAD

**Issue by mlhatfield** [cloudfoundry-community/mattermost-boshrelease#20]
Receiving error when deploying mattermost-load-test. 

> Using deployment 'mattermost-load-test'
>Task 6390492
>
>Task 6390492 | 17:05:44 | Preparing deployment: Preparing deployment
>Task 6390492 | 17:05:46 | Warning: IP address not available for the link provider instance: >mattermost-staging/75a1460c-8f08-48b7-9574-dd603879bff8
>Task 6390492 | 17:05:46 | Warning: IP address not available for the link provider instance: >mattermost-staging/a4cf6c50-edba-4f55-9d38-593d475bd1e4
>Task 6390492 | 17:05:46 | Warning: Ambiguous request: the requested errand name 'load_test' >matches both a job name and an errand instance group name. Executing errand on all relevant >instances with job 'load_test'.
>Task 6390492 | 17:05:56 | Preparing deployment: Preparing deployment (00:00:12)
>                    L Error: Blobstore object '78f1693c-ae96-4c72-9afb-ffaf4d711431' not found
>Task 6390492 | 17:05:56 | Error: Blobstore object '78f1693c-ae96-4c72-9afb-ffaf4d711431' not >found
>
>Task 6390492 Started  Mon Jun 25 17:05:44 UTC 2018
>Task 6390492 Finished Mon Jun 25 17:05:56 UTC 2018
>Task 6390492 Duration 00:00:12
>Task 6390492 error
>
>Running errand 'load_test':
> Expected task '6390492' to succeed but state is 'error'
>
>Exit code 1

We were able to take care of the "_Warning: Ambiguous request: the requested errand name 'load_test' matches both a job name and an errand instance group name. Executing errand on all relevant instances with job 'load_test'._" by updating the instance_groups name "load_test" to something different. 

Currently using version: `6.6.0`

**Comment by drnic** [comment]
Will investigate when back from vacation

**Comment by mlhatfield** [comment]
Thanks for the extra set of eyes @drnic. I ended up deleting the MM releases and deployment from bosh, running `bosh reset-release`, and then re-created+uploaded the release. 

We've created our own load_test_manifest.yml which references the load_test job https://github.com/cloudfoundry-community/mattermost-boshrelease/tree/master/jobs/load_test

The load_test job is now failing with the following error: (found in loadtest.stdout.log)
`{"level":"info","ts":1530548412.2249315,"caller":"loadtest/loadtest.go:97","msg":"Running test","test":"all"}`
Unable to open database: sql: unknown driver "" (forgotten import?)

**Comment by drnic** [comment]
@mlhatfield if you help me reproduce what you've got I can look into fixing the release
