### ISSUE TITLE
Propose updating to Mattermost 3.5

### ISSUE THREAD

**Issue by jasonblais** [cloudfoundry-community/mattermost-boshrelease#4]
Hey @drnic and others,

Just wanted to inform you that Mattermost 3.5 release has been cut.

The new release contains security updates and several API changes - you can [view the full changelog for Mattermost 3.5 here](https://docs.mattermost.com/administration/changelog.html#release-v3-5-0) and [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/9ye3kypwpfdqdyxxh9wwqc9qpe)

Wondering if you'd like to help update the Cloud Foundry BOSH to be compatible with Mattermost 3.5?

If you do update, please consider tweeting about it, which we can then retweet for greater reach.

Also, feel free to join the [Mattermost Installers community channel](https://pre-release.mattermost.com/core/channels/installers-and-images) for latest news relevant for installer owners.

**Comment by jasonblais** [comment]
Hey @drnic, 

wanted to let you know that Mattermost 3.5.1 with bug fixes and security updates is available now: https://docs.mattermost.com/administration/changelog.html#release-v3-5-1

**Comment by drnic** [comment]
Thanks. Sorry our CI had a clean out (thx @lnguyen) and the mattermost pipeline got dropped.

**Comment by jhunt** [comment]
I will get the pipelines back up tomorrow.

**Comment by lindy65** [comment]
Thanks @drnic and @jhunt 

Mattermost 3.7.3 has been released which contains a security update.  You can view the full changelog for v3.7 [here](https://docs.mattermost.com/administration/changelog.html#release-v3-7-3) and find download links with hash numbers [here](https://pre-release.mattermost.com/core/pl/949khgjrntyzbpd3qby4pnwq4w)

Wondering if you'd like to help update the Cloud Foundry BOSH to be compatible with Mattermost 3.7?

If you do update, please consider tweeting about it, which we can then retweet for greater reach.

Also, feel free to join the [Mattermost Installers community channel](https://pre-release.mattermost.com/core/channels/installers-and-images) for latest news relevant to installer owners.

**Comment by norman-abramovitz** [comment]
Closing issue since working on the Mattermost 3.9 release
