### ISSUE TITLE
Add maintainer

### ISSUE THREAD

**Issue by tejaycar** [cloudfoundry-community/mattermost-boshrelease#6]
We've submitted a major PR to add new functionality to this bosh release and modernize it.  Any chance we can get our team added as maintainers on this project vs. creating our own fork?

**Comment by norman-abramovitz** [comment]
Sure

**Comment by norman-abramovitz** [comment]
Sent you an invite to this org.   I created a team for you.  You should be able to invite the rest of your team, once everything is approved.

**Comment by tejaycar** [comment]
So, what's the next step here?  I think I got everything done on my end,
but I still can't add other team members, and I don't think I can commit
changes either.

Thanks,
Tejay

On Thu, Jun 29, 2017 at 2:41 PM, Norman Abramovitz <notifications@github.com

**Comment by drnic** [comment]
@tejaycar I've upgraded you to an Owner of the org so you can invite other members of the org, commit changes etc.

**Comment by tejaycar** [comment]
That's great.  I'm not a bosh expert yet, so I do have one question.  How
do I push new blobs to the blobstore?  I assume that requires some sort of
permissions outside of github, right?

**Comment by drnic** [comment]
@tejaycar sorry that BOSH is new to you. I've done around of upgrades to the BOSH release - bumped to v4.1.0 and moved to bosh2 deployment manifests. The manifest now includes postgresql so the deployment "just works" without an additional step of provisioning SQL somewhere else.

What I'd like to do is automatically update the mattermost blob based on new releases - but I can only find the final builds from the custom URLs e.g. https://releases.mattermost.com/4.1.0/mattermost-4.1.0-linux-amd64.tar.gz

Is this backed by an S3 bucket? If you can give me the bucket info + the path within the bucket to an example file (e.g. mattermost-4.1.0-linux-amd64.tar.gz) then I can add a CI job that automatically finds new releases and adds the blob to the release, and then attempts to build + testflight the release.

Current CI https://ci.starkandwayne.com/teams/main/pipelines/mattermost-boshrelease

**Comment by tejaycar** [comment]
I am personally new to BOSH, but my team has been using it for a few years
now.  This project is just my first chance to really get my feet wet.  BOSH
itself seem pretty straight forward, but the ecosystem around it, and the
structure of these community BOSH releases is a bit harder to wrap my head
around.

In any case, I have no idea where the mattermost releases are served from.
They are available at
https://docs.mattermost.com/administration/upgrade.html#version-archive,
but I'm not involved in the team that actually serves them.

Does a new merge to master kick off a new release in the CI?  IE, if I
update the repo, will that cut a new final release of the bosh release?

Is there any documentation on how to manage a community bosh release?

Thanks,
Tejay

**Comment by drnic** [comment]
@tejaycar I think on behalf of many people I might write up a "how to contribute to cf-community/starkandwayne boshreleases" - over the last few weeks many of them have had their CI pipelines upgraded and include nice things like automatic upstream blob detection (if there is a concourse resource that can do it) and pull-request testing. I'll reply back when I write something.
