### ISSUE TITLE
Update mattermost blob automatically via CI

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/mattermost-boshrelease#7]
@it33 @lindy65 I'm looking to automatically bump the mattermost version whenever they are cut upstream. Currently I can only find the releases via https://about.mattermost.com/download/ but I don't have a great way to automatically detect new ones via Concourse. https://releases.mattermost.com/ shows an AWS S3 error page; so I'm hopeful that behind the URL is an S3 bucket that I can watch with https://github.com/concourse/s3-resource

If there is no public access to the S3 bucket, perhaps Mattermost can create a new IAM user with read permissions for the bucket so CI can poll for new releases.

Shiny new CI https://ci.starkandwayne.com/teams/main/pipelines/mattermost-boshrelease

**Comment by it33** [comment]
Thanks @drnic, I've opened a ticket to discuss: https://gitlab.com/mattermost/proposals/issues/10

I think the trick is handling the possibility of breaking changes across a major version release, e.g. 4.x to 5.x perhaps something changes and we don't want all the downstream automated updaters to break. 

Would need to figure out a protocol to auto-update on minor releases, and maybe dot releases, but have a check on major releases. 

3.x to 4.x was largely uneventful, but 2.x to 3.x there were manual changes required. 

We'd like 4.x to 5.x to be smooth, but we also don't want to limit options for the project, or break automated updaters... 

PS: From your profile it looks like you're in Palo Alto. If so, want to hang out some time, maybe catch up a Stanford Mall one afternoon or evening?

**Comment by drnic** [comment]
We'll have CI run automatically after new releases so we will have an
attempt to discover breaks. Automatically updating the new release blob
will not mean we automatically ship this off to end users; it will just
lower the effort, plus will trigger notifications in the
#mattermost-boshrelease slack channel (in slack.cloudfoundry.org).

**Comment by drnic** [comment]
@it33 sadly I moved away from Palo Alto last year; but I do visit a few
times a year. I'll ping you when I come over next!

**Comment by it33** [comment]
Cool, will wait to see what Chris and Corey say on the new thread: https://gitlab.com/mattermost/proposals/issues/10

Yes, please let me know if you'll be back in Palo Alto, you can reach me at it33 at mattermost.com

**Comment by drnic** [comment]
This is done now via http://ci.starkandwayne.com/teams/main/pipelines/mattermost-releases
